# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-09-29 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('time', models.DateTimeField(auto_now=True)),
                ('news', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemName', models.CharField(max_length=60)),
                ('problemStatement', models.CharField(max_length=60)),
                ('problemDate', models.DateField(auto_now=True, max_length=1)),
                ('extraInformation', models.CharField(max_length=1000)),
                ('timelimit', models.FloatField(default=1)),
                ('input', models.CharField(default='null', max_length=60)),
                ('output', models.CharField(default='null', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'AC'), ('Time limit exceeded', 'TLE'), ('Wrong answer', 'WA')], max_length=20)),
                ('submittedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Language', models.CharField(default='C++', max_length=20)),
                ('Time', models.FloatField(default=0.0)),
                ('Memory', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('sex', models.CharField(choices=[('male', 'm'), ('female', 'f')], max_length=6)),
                ('registeredDate', models.DateField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=60)),
                ('userLevel', models.CharField(choices=[('Admin', 'Admin'), ('Modifier', 'Modifier'), ('Member', 'Member')], default='Member', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tag',
            field=models.ManyToManyField(to='polls.Tag'),
        ),
    ]
