# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-09 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_submission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
