# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20151009_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rank',
            field=models.CharField(choices=[('Ulaan', 'Ulaan'), ('Shar', 'Shar'), ('Tsenher', 'Tsenher'), ('Nogoon', 'Nogoon'), ('Saaral', 'Saaral')], default='Saaral', max_length=20),
        ),
    ]
