# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-10 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_submission_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='rank',
        ),
    ]
